
-- This file is generated by the DataFiller free software.
-- This software comes without any warranty whatsoever.
-- Use at your own risk. Beware, this script may destroy your data!
-- License is GPLv3, see http://www.gnu.org/copyleft/gpl.html
-- Get latest version from http://www.coelho.net/datafiller.html

-- Data generated by: /usr/local/bin/datafiller
-- Version 2.0.1-dev (r832 on 2015-11-01)
-- For postgresql on 2017-05-03T12:34:39.879063 (UTC)
-- 
-- fill table data.user (1)
-- \echo # filling table data.user (1)
-- COPY data.user (id,name,email,"password") FROM STDIN (FREEZE ON);
-- 1	alice	alice@email.com	pass
-- 2	bob	bob@email.com	pass
-- \.
-- -- 
-- -- fill table data.todo (6)
-- \echo # filling table data.todo (6)
-- COPY data.todo (id,todo,private,owner_id) FROM STDIN (FREEZE ON);
-- 9	updated1	FALSE	1
-- 2	item_2	TRUE	1
-- 3	item_3	FALSE	1
-- 4	item_4	TRUE	2
-- 5	item_5	TRUE	2
-- 6	item_6	FALSE	2
-- \.
-- -- 
-- -- restart sequences
-- ALTER SEQUENCE data.user_id_seq RESTART WITH 3;
-- ALTER SEQUENCE data.todo_id_seq RESTART WITH 7;
-- -- 
-- -- analyze modified tables
-- ANALYZE data.user;
-- ANALYZE data.todo;

-- -- ...
set search_path = data, public;
-- INSERT INTO client (id,name,address,user_id) VALUES
-- (1,'Apple','1 Infinite Loop Cupertino, CA 95014',1),
-- (2,'Microsoft','One Microsoft Way Redmond, WA 98052-6399',1),
-- (3,'Amazon','PO Box 81226 Seattle, WA 98108-1226',2)
-- ;

-- INSERT INTO project (id,name,client_id,user_id) VALUES
-- (1,'MacOS',1,1),
-- (2,'Windows',2,1),
-- (3,'IOS',1,1),
-- (4,'Office',2,1)
-- ;

INSERT INTO atlanta_metro_area_tract (id, FileDate, tractID, COUNTYFP10, TotalFilings,TotalAnsweredFilings,indexID) VALUES
(1,'Design a nice UI',TRUE,1,1,1,1),
(2,'Write some OS code',FALSE,1,1,1,2),
(3,'Start aggressive marketing',TRUE,2,1,1,3),
(4,'Get everybody to love it',TRUE,3,1,1,4),
(5,'Move everything to cloud',TRUE,4,1,1,5)
;

INSERT INTO fulton_county_case (FileDate, caseID) VALUES
(1,'Design a nice UI'),
(2,'Write some OS code'),
(3,'Start aggressive marketing'),
(4,'Get everybody to love it'),
(5,'Move everything to cloud')
;

INSERT INTO atlanta_metro_area_case (id, street, city, zip, filingdate, answer, county, latitude,longitude,services,dismiss,defaultJudgment,judgment,answerdate,servicesdate,dismissdate,defaultJudgmentdate,judgmentdate) VALUES
(1,'Design a nice UI2',TRUE,1,1,1,1,-83,123,1,1,1,1,'2001-10-05','2001-10-05','2001-10-05','2001-10-05','2001-10-05'),
(2,'Write some OS code',FALSE,1,1,1,2,-83,123,1,1,1,1,'2001-10-05','2001-10-05','2001-10-05','2001-10-05','2001-10-05'),
(3,'Start aggressive marketing',TRUE,2,1,1,3,-83,123,1,1,1,1,'2001-10-05','2001-10-05','2001-10-05','2001-10-05','2001-10-05'),
(4,'Get everybody to love it',TRUE,3,1,1,4,-83,123,1,1,1,1,'2001-10-05','2001-10-05','2001-10-05','2001-10-05','2001-10-05'),
(5,'Move everything to cloud',TRUE,4,1,1,5,-83,123,1,1,1,1,'2001-10-05','2001-10-05','2001-10-05','2001-10-05','2001-10-05')
;


-- INSERT INTO project_comment (id,body,project_id,user_id) VALUES
-- (1,'This is going to be awesome',1,1),
-- (2,'We still have the marketshare, we should keep it that way',2,1)
-- ;

-- INSERT INTO task_comment (id,body,task_id,user_id) VALUES
-- (1,'Arn''t we awesome?',1,1),
-- (2,'People are going to love the free automated install when they see it in the morning',3,1)
-- ;
